kind: PersistentVolume
apiVersion: v1
metadata:
  name: platformconfig-azurefile-pv
  uid: 3b1c4819-dbf0-4303-b27f-51a610fe2b48
  resourceVersion: '428884596'
  creationTimestamp: '2025-06-13T12:34:45Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:34:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:34:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:34:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.110
    path: /var/platformconfig-azurefile
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: tprms
    name: platformconfig-azurefile-pvc
    uid: 0274d739-bc9e-4727-93bc-806417830c77
    apiVersion: v1
    resourceVersion: '428884594'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
