apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrowflight
  namespace: tprms
  labels:
    service: arrowflight
spec:
  replicas: 1
  selector:
    matchLabels:
      service: arrowflight
  template:
    metadata:
      labels:
        service: arrowflight
    spec:
      containers:
        - name: arrowflight
          image: repo.vinsys.com/arrowflight:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
