apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-scheduler
  namespace: tprms
  labels:
    service: redis-scheduler

spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-scheduler

  template:
    metadata:
      labels:
        service: redis-scheduler

    spec:
      containers:
        - name: redis-scheduler
          image: repo.vinsys.com/redis:5.0.4-stretch
          imagePullPolicy: IfNotPresent

          command:
            - redis-server
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD_SCHEDULER)"

          env:
            - name: REDIS_PASSWORD_SCHEDULER
              value: "$(REDIS_PASSWORD_SCHEDULER)"
            - name: TZ
              value: UTC

          envFrom:
            - secretRef:
                name: secrets-production-redis

          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
