apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb
  namespace: tprms
  labels:
    service: keydb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: keydb
  template:
    metadata:
      labels:
        service: keydb
    spec:
      containers:
        - name: keydb
          image: repo.vinsys.com/keydb:latest
          imagePullPolicy: Always
          command:
            - keydb-server
          args:
            - "--requirepass"
            - "$(KEYDB_PASSWORD)"
          env:
            - name: KEYDB_PASSWORD
              value: "$(KEYDB_PASSWORD)"
          envFrom:
            - secretRef:
                name: secrets-production-redis
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
