apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tprms
  labels:
    service: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      volumes:
        - name: nginx-conf-azurefile
          persistentVolumeClaim:
            claimName: nginx-conf-azurefile-pvc
        - name: media-azurefile-pvc
          persistentVolumeClaim:
            claimName: media-azurefile-pvc
        - name: static-azurefile-pvc
          persistentVolumeClaim:
            claimName: static-azurefile-pvc

      containers:
        - name: nginx
          image: repo.vinsys.com/nginx:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-conf-azurefile
              mountPath: /etc/nginx/
            - name: media-azurefile-pvc
              mountPath: /var/www/revolutio/media
            - name: static-azurefile-pvc
              mountPath: /var/www/revolutio/static
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      restartPolicy: Always

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
