kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  resourceVersion: '509311275'
  name: redis-scheduler
  uid: 94a4740a-14b7-4fd3-bc02-720e13792c65
  creationTimestamp: '2025-06-13T11:08:14Z'
  generation: 1
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2025-06-13T11:08:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:service': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:service': {}
            'f:spec':
              'f:containers':
                'k:{"name":"redis-scheduler"}':
                  'f:envFrom': {}
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:args': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"REDIS_PASSWORD_SCHEDULER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-26T02:17:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: tprms
  labels:
    service: redis-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-scheduler
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis-scheduler
    spec:
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: redis-scheduler
          command:
            - redis-server
          env:
            - name: REDIS_PASSWORD_SCHEDULER
              value: $(REDIS_PASSWORD_SCHEDULER)
            - name: TZ
              value: UTC
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: secrets-production-redis
          image: 'repo.vinsys.com/redis:5.0.4-stretch'
          args:
            - '--requirepass'
            - $(REDIS_PASSWORD_SCHEDULER)
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-06-13T11:08:17Z'
      lastTransitionTime: '2025-06-13T11:08:14Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "redis-scheduler-76b5665c7b" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-08-26T02:17:28Z'
      lastTransitionTime: '2025-08-26T02:17:28Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
