kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
  resourceVersion: '508969371'
  name: rqscheduler
  uid: 528a0bcf-e798-47f2-b464-efcd5646b30c
  creationTimestamp: '2025-06-20T06:04:00Z'
  generation: 13
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2025-06-20T06:04:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:service': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:service': {}
            'f:spec':
              'f:containers':
                'k:{"name":"rqscheduler"}':
                  'f:envFrom': {}
                  'f:image': {}
                  'f:volumeMounts': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:args': {}
                  'f:env':
                    .: {}
                    'k:{"name":"REDIS_URL_SCHEDULER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8899,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-06-20T06:12:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"rqscheduler"}':
                  'f:volumeMounts':
                    'k:{"mountPath":"/opt/revolutio/Core/templates/user_defined_template"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/opt/revolutio/Platform_Configs"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/opt/revolutio/static"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:volumes':
                'k:{"name":"platformconfig-azurefile-pvc"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"static-azurefile-pvc"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"templates-azurefile-pvc"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-25T18:02:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: tprms
  labels:
    service: rqscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rqscheduler
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rqscheduler
    spec:
      volumes:
        - name: static-azurefile-pvc
          persistentVolumeClaim:
            claimName: static-azurefile-pvc
        - name: templates-azurefile-pvc
          persistentVolumeClaim:
            claimName: templates-azurefile-pvc
        - name: platformconfig-azurefile-pvc
          persistentVolumeClaim:
            claimName: platformconfig-azurefile-pvc
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: rqscheduler
          env:
            - name: REDIS_URL_SCHEDULER
              value: $(REDIS_URL_SCHEDULER)
            - name: TZ
              value: UTC
          ports:
            - name: rqscheduler
              containerPort: 8899
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: static-azurefile-pvc
              mountPath: /opt/revolutio/static
            - name: templates-azurefile-pvc
              mountPath: /opt/revolutio/Core/templates/user_defined_template
            - name: platformconfig-azurefile-pvc
              mountPath: /opt/revolutio/Platform_Configs
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: envs-production-web
          image: 'repo.vinsys.com/rqscheduler:latest'
          args:
            - /app/start
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 13
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-06-20T06:12:53Z'
      lastTransitionTime: '2025-06-20T06:04:00Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "rqscheduler-6878d5dcd4" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-08-25T18:02:54Z'
      lastTransitionTime: '2025-08-25T18:02:54Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
