kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  resourceVersion: '508969379'
  name: pgbouncer
  uid: d854caee-a2d4-4a60-99c0-9dd819d18cb2
  creationTimestamp: '2025-08-19T10:11:06Z'
  generation: 1
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-19T10:11:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"pgbouncer"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:lifecycle':
                    .: {}
                    'f:preStop':
                      .: {}
                      'f:exec':
                        .: {}
                        'f:command': {}
                  'f:env':
                    'k:{"name":"SERVER_RESET_QUERY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"IGNORE_STARTUP_PARAMETERS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"DB_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MAX_CLIENT_CONN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"POOL_MODE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"default_pool_size"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DB_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"DB_USER"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":5432,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-25T18:02:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: tprms
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgbouncer
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - killall -INT pgbouncer && sleep 120
          name: pgbouncer
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: envs-production-postgres-new
                  key: POSTGRES_HOST_INNER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-production-postgres-new
                  key: POSTGRES_PASSWORD
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: envs-production-postgres-new
                  key: POSTGRES_USER
            - name: POOL_MODE
              value: transaction
            - name: SERVER_RESET_QUERY
              value: DISCARD ALL
            - name: IGNORE_STARTUP_PARAMETERS
              value: options
            - name: MAX_CLIENT_CONN
              value: '100'
            - name: default_pool_size
              value: '50'
          securityContext:
            capabilities:
              drop:
                - all
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'repo.vinsys.com/pgbouncer:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-08-19T10:11:10Z'
      lastTransitionTime: '2025-08-19T10:11:06Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "pgbouncer-694449dccd" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-08-25T18:02:54Z'
      lastTransitionTime: '2025-08-25T18:02:54Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
