kind: Secret
apiVersion: v1
metadata:
  name: dynatrace-dynakube-config
  namespace: tprms
  uid: 8d07df94-835e-40a6-a16b-92d3ebc99bc4
  resourceVersion: '448841825'
  creationTimestamp: '2025-07-02T09:48:58Z'
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: lab-wcqdc
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: v1.6.0
  annotations:
    internal.operator.dynatrace.com/template-hash: '2557610196'
  managedFields:
    - manager: dynatrace-operator
      operation: Update
      apiVersion: v1
      time: '2025-07-02T09:48:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:agcerts': {}
          'f:config': {}
          'f:proxy': {}
          'f:trustedcas': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:internal.operator.dynatrace.com/template-hash': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/created-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
        'f:type': {}
data:
  agcerts: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdMekNDQkJlZ0F3SUJBZ0lRUjhQcTJEOWhMSGQ1NnExUWRqVTFuekFOQmdrcWhraUc5dzBCQVFzRkFEQjUKTVFzd0NRWURWUVFHRXdKQlZERUxNQWtHQTFVRUNCTUNWVUV4RFRBTEJnTlZCQWNUQkV4cGJub3hFakFRQmdOVgpCQW9UQ1VSNWJtRjBjbUZqWlRFUk1BOEdBMVVFQ3hNSVQzQmxjbUYwYjNJeEp6QWxCZ05WQkFNVEhteGhZaTEzClkzRmtZeTFoWTNScGRtVm5ZWFJsTG1SNWJtRjBjbUZqWlRBZ0Z3MHlOVEEzTURJd09UUTNNVGRhR0E4eU1USTEKTURZd09EQTVORGN4TjFvd2VURUxNQWtHQTFVRUJoTUNRVlF4Q3pBSkJnTlZCQWdUQWxWQk1RMHdDd1lEVlFRSApFd1JNYVc1Nk1SSXdFQVlEVlFRS0V3bEVlVzVoZEhKaFkyVXhFVEFQQmdOVkJBc1RDRTl3WlhKaGRHOXlNU2N3CkpRWURWUVFERXg1c1lXSXRkMk54WkdNdFlXTjBhWFpsWjJGMFpTNWtlVzVoZEhKaFkyVXdnZ0lpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQzg4YWtpaVJhUUNoZmFhdC9MV3lWWlRyUW9NeGZ5V0F2UApMRzJydDZQc3hUdmZPbzlPOVQvZzRyNWJQbmFtVVM3azVDekR4bVlESXBRdUt6L2dHdUtMZHFMUlZhcGJGcmM2CkNnbVNoSG5BTUY2aDBNOUdtUUVaUTdiakVyZlVWZmFDZm0rdDRYOTd2QUhZell6bW91d25OdlpYNWdxT1I0WEMKV2JJSXl5WmEvam9Yejd6N0wvbWlsNVBCK3BsckxZcHM5RHNrOTMxMHhnc2YxbHY0Sm9lUHpmOHErcUZtcTJGNApiZ3lVakE4SllCb2g4Zm90Q3BzNmREb21NZ3F6N0lPNXZabEE4bjlzWDRhN0Z3cmVRN3B2RFkzZEtFZkdlRS9KCmVVNnIva3lsdC9ncGRINUlHZlpaRkg1ZWlxNFJqSnpPZHgraDNGdS8rNDFieUo0Q3FvdzZUVlRkS1p4QmFobW8KZGhwNkhEUW02M0JGQktzNVdQYW95TFMwdGJIQ0pBa2NTNllNTXFVTHJLbnYybVZqa2IzbUFHZExMc1VkZUEwNwpNWk5JZFlJaXpISmwzc2dXSmIvcG1LVnBIS2R3ckFiV1JaUVJKd0t5SFYyTVBFcEhSVXlTbFFXQklVc1V6M015CnlrelNsVVNhUm1hSE1lcUJockczUjZUeDlqdnV0MzJocGFrYjVZWFVGUVgwZUVybWp4Y05ZckZtLyt5RkxZWnMKMlZqTTFuRnVZVUxhOXJRcW5QNTBNTHVubWZvckJ0N0FPaFNqZW1EOWxxbGVyWGNZQlRSRTZCL1QxaVc5S2cxeApXandya2dSRWFxRkNYUXJudWcxckU2SW5DOVRmMUdPYjE0Q3N0dU1EaEQ0aG9Qcy81eGtLTlBLQWZKUGY0Q1k4CnJ2U1FKdWRNNVFJREFRQUJvNEd3TUlHdE1BNEdBMVVkRHdFQi93UUVBd0lFTURBVEJnTlZIU1VFRERBS0JnZ3IKQmdFRkJRY0RBVENCaFFZRFZSMFJCSDR3ZklJZWJHRmlMWGRqY1dSakxXRmpkR2wyWldkaGRHVXVaSGx1WVhSeQpZV05sZ2lKc1lXSXRkMk54WkdNdFlXTjBhWFpsWjJGMFpTNWtlVzVoZEhKaFkyVXVjM1pqZ2pCc1lXSXRkMk54ClpHTXRZV04wYVhabFoyRjBaUzVrZVc1aGRISmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lIQkt3ZUpDSXcKRFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUg0MURLRDU2eXljRC9leXl1Vm1KN25EbVJJbjBnUlBRK3FOT3ZsSgpWRnRtYnhqd0Vhc0dYYkJPSjQzenJxcUljbmNRNEVWRFJjUDQwQXh5S2QvMWsvdEF6TEFZZGZRc0d6Sko4NzF5CmtBaDhvblpGYjhkL1Zua3ZMQ1oyVDJqWGFOMHhSYlhPem1hSEpDSGloYnBqUEptNUFsU1gzSDZJZktrZzNyWDYKYW9QWGVaQ2xqRThZOHNKNW52b2dqbzdZVXorRXJveERXL2lKY0cwQTdNcktKWTNiTXJWdUZlYm9kUDYzTUpnUQpKRVFpdjRyeFdiWnhqdGdONXNmcDF6NGpLRXhldWg5RVFpVHpyYWlkZnF0Y2kwU3ZjK0o4cmN4cnVKdGRnK2FICko3YUpGU1NYR1JoRzcvTnZZWnN0aTRDenVUamFjRXpTa3VrY1Q1R2dpQnhWNm5STUpPSTk0WkRDaXNoR1h3SDMKY3ZFNW0zTGFsdHoxTytoWk41WHYvUUljaUhLUzd4OVFyZjBMaHVqM3VlMTdpRm01ckhSYjRmUUEwTnBTQlBvMQpnUHhIZ0xCaVJLazhjNW14My84RGVGei9oMjFlYW5zQ1kxZHQ5SVpSZzhYZlJ6VmFWRldxSE1CN1U0Vll4SVY1CldGUC9mUTZpdEdHb3I1Uk5CYlg2a1AyRXdZSVFIU2FBUkZSSm9iSEZqSUhITStSOVQ0dW9uOSttOWlHbWJadUQKWUhqZHM1RkJIOHAvSlBDb1RuaENncTJNWDVnZnNJakU0YVlpZWNZV1JSK0kvbGV0TEZSNmowUVlWcTl5V1lQWApRYlRqRnhxb2lWSGF4c0E0cVdkUU9veXhjeks1VGo0SjU4NGJUNTNrS1lZWHU4M3RYaldvczVQT254MVNXdVNUCmlUOE8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  config: eyJtb25pdG9yaW5nTm9kZXMiOnsib2NwNC1jb21wdXRlLTEiOiJpdmk4NDQ5MSIsIm9jcDQtY29tcHV0ZS0yIjoiaXZpODQ0OTEiLCJvY3A0LWNvbXB1dGUtNCI6Iml2aTg0NDkxIiwib2NwNC1jb250cm9sLXBsYW5lLTEiOiJpdmk4NDQ5MSIsIm9jcDQtY29udHJvbC1wbGFuZS0yIjoiaXZpODQ0OTEiLCJvY3A0LWNvbnRyb2wtcGxhbmUtMyI6Iml2aTg0NDkxIn0sImFwaVVybCI6Imh0dHBzOi8vaXZpODQ0OTEubGl2ZS5keW5hdHJhY2UuY29tL2FwaSIsImFwaVRva2VuIjoiZHQwYzAxLkoyTlUzRzJaWk5XT0JSUlJZUlZKSklNSi5FNlJQMjYyVEFHVEhGWUVNSjRXSUgyTklJNUFUVDJUSlpCNllSU05RT1dEVkVUQVZFN0Q1UVFESlRRTTRUN1JEIiwicGFhc1Rva2VuIjoiZHQwYzAxLkoyTlUzRzJaWk5XT0JSUlJZUlZKSklNSi5FNlJQMjYyVEFHVEhGWUVNSjRXSUgyTklJNUFUVDJUSlpCNllSU05RT1dEVkVUQVZFN0Q1UVFESlRRTTRUN1JEIiwicHJveHkiOiIiLCJub1Byb3h5IjoiIiwibmV0d29ya1pvbmUiOiIiLCJvbmVBZ2VudE5vUHJveHkiOiIxNzIuMzAuMzYuMzQsbGFiLXdjcWRjLWFjdGl2ZWdhdGUuZHluYXRyYWNlIiwidGVuYW50VVVJRCI6Iml2aTg0NDkxIiwiaG9zdEdyb3VwIjoiIiwiaW5pdGlhbENvbm5lY3RSZXRyeSI6LTEsInNraXBDZXJ0Q2hlY2siOmZhbHNlLCJoYXNIb3N0Ijp0cnVlLCJlbmZvcmNlbWVudE1vZGUiOnRydWUsImNzaU1vZGUiOnRydWUsInJlYWRPbmx5Q1NJRHJpdmVyIjpmYWxzZX0=
  proxy: ''
  trustedcas: ''
type: Opaque
